import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/ui/footer";
import { getServerAuthSession } from "@/server/auth";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { Inter } from "next/font/google";
import Navbar from "../components/ui/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const session = await getServerAuthSession()


  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <ThemeProvider attribute="class" enableSystem defaultTheme="system" disableTransitionOnChange>
            <main>
              <Navbar session={session} />
              {children}
              <Footer />
            </main>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

